# Generated by Django 5.1.3 on 2024-11-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
